/user/change-password:
    path: '/change-password'
    defaults: { _controller: ApiUserBundle:ChangePassword:changePassword }
    methods: [POST]

/user/confirm:
    path: '/confirm/{token}'
    defaults: { _controller: ApiUserBundle:Registration:confirm }
    methods: [POST]

/user/forgot:
    path: '/forgot'
    defaults: { _controller: ApiUserBundle:ForgotPassword:forgot }
    methods: [POST]

/user/register:
    path: '/register'
    defaults: { _controller: ApiUserBundle:Registration:register }
    methods: [POST]

/user/reset:
    path: '/reset/{token}'
    defaults: { _controller: ApiUserBundle:ForgotPassword:reset }
    methods: [POST]

/user/update:
    path: '/'
    defaults: { _controller: ApiUserBundle:Update:update }
    methods: [PATCH]