parameters:
    # Controller
    api_user.controller.dto.change_password.class: 'PhpSolution\ApiUserBundle\Dto\ChangePasswordDto'
    api_user.controller.dto.reset_password.class: 'PhpSolution\ApiUserBundle\Dto\ResetPasswordDto'
    api_user.controller.dto.registration.class: 'PhpSolution\ApiUserBundle\Dto\RegistrationDto'
    api_user.controller.dto.update.class: 'PhpSolution\ApiUserBundle\Dto\UpdateDto'

services:
    # Controller
    api_user.controller.change_password:
        class: 'PhpSolution\ApiUserBundle\Controller\ChangePasswordController'
        arguments:
            - '%api_user.controller.dto.change_password.class%'

    api_user.controller.forgot_password:
        class: 'PhpSolution\ApiUserBundle\Controller\ForgotPasswordController'
        arguments:
            - '%api_user.controller.dto.reset_password.class%'

    api_user.controller.registration:
        class: 'PhpSolution\ApiUserBundle\Controller\RegistrationController'
        arguments:
            - '%api_user.controller.dto.registration.class%'

    api_user.controller.update:
        class: 'PhpSolution\ApiUserBundle\Controller\UpdateController'
        arguments:
            - '%api_user.controller.dto.update.class%'

    # Process
    api_user.process.change_password:
        class: 'PhpSolution\ApiUserBundle\Process\ChangePasswordProcess'
        arguments:
            - '@api_user.service.user'
            - '@event_dispatcher'

    api_user.process.confirm_registration:
        class: 'PhpSolution\ApiUserBundle\Process\ConfirmRegistrationProcess'
        arguments:
            - '@api_user.service.user'
            - '@event_dispatcher'

    api_user.process.forgot_password:
        class: 'PhpSolution\ApiUserBundle\Process\ForgotPasswordProcess'
        arguments:
            - '@api_user.service.user'
            - '@api_user.util.token_generator'
            - '@event_dispatcher'

    api_user.process.registration:
        class: 'PhpSolution\ApiUserBundle\Process\RegistrationProcess'
        arguments:
            - '@api_user.util.user_factory'
            - '@api_user.service.user'
            - '@event_dispatcher'

    api_user.process.update:
        class: 'PhpSolution\ApiUserBundle\Process\UpdateProcess'
        arguments:
            - '@api_user.service.user'
            - '@event_dispatcher'

    # Security
    ## User
    api_user.security.user_provider:
        class: 'PhpSolution\ApiUserBundle\Security\User\UserProvider'
        arguments:
            - '%api_user.user_entity_class%'
            - '@doctrine'

    # Service
    api_user.service.user:
        class: 'PhpSolution\ApiUserBundle\Service\UserService'
        arguments:
            - '@validator'
            - '%api_user.user_entity_class%'
            - '@security.encoder_factory'
        calls:
            - ['setDoctrine', ['@doctrine']]

    # Util
    api_user.util.token_generator:
        public: false
        class: 'Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator'

    api_user.util.user_factory:
        class: 'PhpSolution\ApiUserBundle\Util\UserFactory'
        arguments:
            - '%api_user.user_entity_class%'
            - '%api_user.user_enabled_by_default%'
        calls:
            - ['setTokenGenerator', ['@api_user.util.token_generator']]