PhpSolution\ApiUserBundle\Entity\AbstractUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
    properties:
        email:
            - NotBlank: ~
            - Email: ~
            - Length:
                min: 2
                max: 255
        plainPassword:
            - NotBlank:
                groups: [Registration, ChangePassword, ResetPassword]
            - Length:
                min: 2
                max: 255
                groups: [Registration, ChangePassword, ResetPassword]