services:
    api_user.event_subscriber.forgot_password:
        class: 'PhpSolution\ApiUserBundle\EventSubscriber\ForgotPasswordSubscriber'
        arguments:
            - '@router'
            - '@mailer'
            - '%mailer_user%'
        tags:
            - { name: kernel.event_subscriber }